"""initial schema

Revision ID: 37fa7b1d983f
Revises: 
Create Date: 2026-08-19 11:39:58.608925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '37fa7b1d983f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tradable', sa.Boolean(), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('last_price_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('investor', 'admin', 'backoffice_operator', 'super_admin', name='role_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'closed', name='account_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_reserved', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cash_balance >= 0', name='ck_accounts_cash_balance_nonneg'),
    sa.CheckConstraint('cash_reserved <= cash_balance', name='ck_accounts_reserved_le_balance'),
    sa.CheckConstraint('cash_reserved >= 0', name='ck_accounts_cash_reserved_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('quotes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('price > 0', name='ck_quotes_price_positive'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of', name='uq_quotes_instrument_as_of')
    )
    op.create_index(op.f('ix_quotes_instrument_id'), 'quotes', ['instrument_id'], unique=False)
    op.create_table('kyc_files',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'validated', 'rejected', name='kyc_status'), nullable=False),
    sa.Column('full_legal_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id_document_type', sa.String(length=50), nullable=True),
    sa.Column('id_document_number', sa.String(length=100), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('orders',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side'), nullable=False),
    sa.Column('order_type', sa.Enum('market', 'limit', name='order_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('estimated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estimated_fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'reserved', 'executed', 'cancelled', 'rejected', name='order_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_positions_quantity_nonneg'),
    sa.CheckConstraint('reserved_quantity <= quantity', name='ck_positions_reserved_le_quantity'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_positions_reserved_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instrument_id', name='uq_positions_account_instrument')
    )
    op.create_table('executions',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_status_history',
    sa.Column('kyc_file_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'submitted', 'validated', 'rejected', name='kyc_status'), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'submitted', 'validated', 'rejected', name='kyc_status'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kyc_file_id'], ['kyc_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('cash', 'shares', name='reservation_kind'), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Enum('active', 'released', 'consumed', name='reservation_status'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('initial_credit', 'trade_buy', 'trade_sell', 'fee', name='ledger_entry_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_reference'), 'ledger_entries', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_reference'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('reservations')
    op.drop_table('kyc_status_history')
    op.drop_table('executions')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_table('kyc_files')
    op.drop_index(op.f('ix_quotes_instrument_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
